language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
sudo: required
services:
- docker
notifications:
  email:
  - 51101661@qq.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
before_install:
- export BUILD_NAME=$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
script:
- sh travis_scripts/tag_build.sh
- sh travis_scripts/build_services.sh
- sh travis_scripts/deploy_to_docker_hub.sh
env:
  global:
  - secure: yYQxJ08Cu9H6/pj7tQRmNRCPV1bH62+65uW1Nhomuc5GgSLoZ9hiXWs0wODIa9HMAfdFvV3C1eKbnMLNBu3vLhaWy1I2vWgzWUWaLlHtn8SlJCUTlzyGnSDUOVGLIAX5elZpzO58Afoa2qPDo7IKtf1bPphalrjnGCKYdtL59QGlqPca6MvsKuCsLaSTgHRWzf0lSZRMTf/4nK405zo5a6ZYS+1N0AINC6y7G5btLPu4XPC8rA2oLo0AZXSazaQ0DiLr+i0VwCDErf2S7mWUCabvsKCleYGTGgZFFHA2pK+DW+7i8lcu0MOhLvpUO2IWmRTQS925fAb3pln/vNeKZgog4gMI99Bpcqs49ECo6TzFZ5wAh8BOiNtddquMg+ZBntmvaJAz+2nlNjo9rt99lKcD8XaMNQ6AhVDVxxb8lQ5xNjU9wmn6/tDcaXd1XBq/wzlosV6kE/9L6dXS+vhpCkVjfTEKyWjJyMeU/mpS1oW5KKIhKjooDrPjTDnXHJgPUjhQD92oX5qo5dczDlBPYU3YcLA2Nv3jASysGziBTaeobVUFDdXleWRywkEiKRTt7zFNmPsMJlj3dvMOJyQLeapTeBnk7QPntlsDUSxHX7QvyyxVvxwoqf9V738fHnMUfVAfj46YYVoSncG7PMRqSzPPMOZiT5lBVFwP1MrF1vE=
  - secure: nL3LneZVqWOgaFo7yGioKYZ1ulH5wWB83MBQY6iSoQR75a6+qebhEdRk+tlCGmGyLrAL9G4RPpwoBjxSAgIP/98z3JRmxhYD4cpDklcaDnD16ClAG9vCamI7Xc9JVdov7RFca8uyCpH2QC48vKtCOXHc1+gztPVpy/NSuYlePjHkvXH04qR+YVywd6K5WPZMWz5xyCJH/7PUUm+ba76Bulg4xtEchrFLn7VFvqguthQw2EToyZKaaT95qPHUcZi/B77qicdgY4k6tWVw3pDzq3CMxX0yqb1bePsITb8PC5HwL+HgY1eQEuaWHlxsXU5w3AFfAUMRIL7TEbWj52NgSf1NDpgmYELd472gt8hpyIFXHLpatL05V5AOjxxISMjMvUK54q0kn2oZKS6hKaSm/q73P7SBZKf3+r2XtsOIojhtMfTr39v0yyn7jETmtTj1Btjb2f0UL2RgssIP1mUNjhbLuIVoqifbngFmzD+QhtJ3LOFBQm7mG659Q0oWXNHDZWf/vCaXj8J+XDoP9IFYuRNju696h8rfwu/c+xXfLSQVhQD5VXarfnsf5SxAHpMyoddE7chquULMdT3YVDpqSCg7gQLDnw2g8FJbnCWJ3fq27KbSfCGZ9lbJOZzNAVshKziWF+OqtbxzG2VniDuq8Zod9HIRG9BYl56yYN06Uc4=
  - secure: LICyZKnthR+v/nwq1tkHHRRLOV4IbFZ2qFjzg7paddek+V3Ri2rWS/PiAVWbD77LIO74cDDjKjH8iTzG78SNJT1il5gkZliktZOkakRicT3NDDADrZfNG4BwBpV+IPUvBWirW/Vm3sRUoOo4O3J2eRX7jzEO9wYHwolzeqgDisGZDTHsC0O4j8dS7Zaew35jiw3/EtqD2bgzkaUwF8nDrcJ8bsRKlgLr5t3iz516Sk0H4YxjTSX63oeBkPRLOTLJPVkfn084F5lcFe9moG+5mMDg878w8b04NumpKPI+MjJq9DcbJ2EaHs8f54tyZKFC81iuHvK7WMWs00avBLu62AJbHax9WRF13MrzzV57PGcNtCzwlIytluL/0nc3A2jL7cLAnRFjIGYv1r6I2NzCfkpXFcX6xGGcBPzFh5jj7QMi3H8dfaSQdwVps/5l0S0NfAimqqI3maCVIZz5D/uPW0egT3ZYB87ZCZpah2krx5EhX9TplP/jgGUJGtBrITwWx0RGm/bYJdyD7T1b9VyQ8n7uDO8IY0nQjZeKuCI5dUKPfULXLX5htfgJL4TbVHFZPPYYMm3YySwlahCK//53vvn2KADvbU1eScTUPVWyxBkHYbtXYSkQWVHUiyjICbilKFglg+23c+WOHgzm0rLNkwzzivtfA0ldS28oXjwBCGM=
